import requests
import sys

BASE_URL = "http://127.0.0.1:8000"

def run_optimizer_tests():
    print("Testing Redistribution Optimizer on live server...")

    # 1. Trigger anomaly scan first (so that Wada PHC ID 5 gets marked unreliable,
    # ensuring the optimizer does not select Wada for transfers!)
    print("Pre-scanning anomalies to set data trust scores...")
    requests.post(f"{BASE_URL}/api/anomaly/analyze")

    # 2. Get recommendations
    print("Fetching ranked transfer recommendations...")
    r = requests.get(f"{BASE_URL}/api/transfers/recommend")
    assert r.status_code == 200, f"Failed to fetch recommendations: {r.text}"
    recommendations = r.json()
    
    print(f"[SUCCESS] Generated {len(recommendations)} transfer recommendations:")
    for rec in recommendations:
        print(f"   - Rank Urgency Score {rec['urgency_score']:.1f} | Drug: {rec['drug_name']}")
        print(f"     - Reasoning: {rec['reasoning']}")

    assert len(recommendations) > 0, "No recommendations generated by PuLP! Seeding may have no deficit/surplus matches."
    
    # Assert Tokawade PHC (ID 7) is a recipient for at least one shortage (e.g. Paracetamol or Amoxicillin)
    tokawade_recs = [rec for rec in recommendations if rec["to_centre_id"] == 7]
    assert len(tokawade_recs) > 0, "Tokawade PHC (ID 7) should have been recommended to receive stock!"
    print("[SUCCESS] Tokawade PHC correctly identified as a target recipient for redistribution.")

    # 3. Test execution of a transfer suggestion
    target_rec = recommendations[0]
    print(f"\nExecuting recommendation ID {target_rec['id']}:")
    print(f"   - Transferring {target_rec['quantity']} {target_rec['drug_unit']} of {target_rec['drug_name']} "
          f"from {target_rec['from_centre_name']} to {target_rec['to_centre_name']}.")

    # Fetch initial stocks
    def get_stock(centre_id, drug_id):
        inv_res = requests.get(f"{BASE_URL}/api/stock/inventory/{centre_id}").json()
        item = next(x for x in inv_res["inventory"] if x["drug_id"] == drug_id)
        return item["current_stock"]

    source_init = get_stock(target_rec['from_centre_id'], target_rec['drug_id'])
    dest_init = get_stock(target_rec['to_centre_id'], target_rec['drug_id'])
    print(f"   - Initial stock - Source: {source_init} | Destination: {dest_init}")

    # Complete the transfer
    patch_url = f"{BASE_URL}/api/transfers/{target_rec['id']}?new_status=completed"
    patch_res = requests.patch(patch_url)
    assert patch_res.status_code == 200, f"Failed to complete transfer: {patch_res.text}"
    print("[SUCCESS] Transfer status successfully updated to 'completed'.")

    # Fetch updated stocks
    source_new = get_stock(target_rec['from_centre_id'], target_rec['drug_id'])
    dest_new = get_stock(target_rec['to_centre_id'], target_rec['drug_id'])
    print(f"   - Updated stock - Source: {source_new} | Destination: {dest_new}")

    # Assert stock logs updated correctly
    assert source_new == source_init - target_rec['quantity'], "Source stock deduction incorrect!"
    assert dest_new == dest_init + target_rec['quantity'], "Destination stock addition incorrect!"
    print("[SUCCESS] Inventory levels updated correctly! Stock transfer verified.")

    print("\n--- ALL REDISTRIBUTION OPTIMIZER TESTS PASSED! ---")

if __name__ == "__main__":
    run_optimizer_tests()
